spring.mongodb.uri=mongodb://localhost:27017/activitydb
server.port=8881

openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
# ===============================
# CORS Configuration
# ===============================
${app.cors.allowed-origin=http://localhost:5173